### ISSUE TITLE
Support for a different aws region provider

### ISSUE THREAD

**Issue by dmitry-mightydevops** [cloudposse/terraform-aws-sns-lambda-notify-slack#19]
## Describe the Feature

My primary aws region is us-west-2, but cloudwatch billing alarm should be created only in us-east-1
It would be nice to define the region (via aws provider) where the resources should be created

```
provider "aws" {
  alias = "east"
  region = "us-east-1"
}

module "notify_slack_east" {
  provider          = aws.east
  source            = "git::https://github.com/cloudposse/terraform-aws-sns-lambda-notify-slack?ref=tags/0.5.0"
  namespace         = var.team
  create_sns_topic  = true
  sns_topic_name    = "${var.team}-slack-notifications"
  name              = "notifications"
  slack_webhook_url = var.slack_webhook_url
  slack_channel     = "alarm"
  slack_username    = module.notify_slack_userrname.id
}
```

## Expected Behavior

Proper resources to be created in proper aws region

**Comment by nitrocode** [comment]
@dmitry-mightydevops not sure what you mean by cloudwatch billing.

This is the upstream module https://github.com/terraform-aws-modules/terraform-aws-notify-slack#resources and it creates all resources according to the provider passed in.

The only cloudwatch resource it's creating is the following

https://github.com/terraform-aws-modules/terraform-aws-notify-slack/blob/f7dd0a35d1c140a3465564740abe3579c9e12b48/main.tf#L54-L62

The upstream module and this module do not provision its own provider so passing one in explicitly, like you did above, should work as expected.

Perhaps the cloudwatch billing alarm is created by another terraform module ?
